"""Constants for the EPA Air Quality integration."""

from datetime import timedelta
from typing import Final

# Integration constants
ATTR_ENTRY_TYPE: Final = "entry_type"
ATTRIBUTION: Final = "Data retrieved from EPA (Victoria)"
COLLECTOR: Final = "collector"
CONF_LEGACY_UNIQUE_IDS: Final = "legacy_unique_ids"
CONF_AQI_SOURCE: Final = "aqi_source"
CONF_SITE_ID: Final = "site_id"
CONF_SITE_NAME: Final = "site_name"
DOMAIN: Final = "epa_victoria_air_quality"
ENTRY_TYPE_SERVICE: Final = "service"
COORDINATOR: Final = "coordinator"
UPDATE_LISTENER: Final = "update_listener"
AQI_SOURCE_OVERALL: Final = "overall"
AQI_SOURCE_PM25: Final = "pm25"
DEFAULT_AQI_SOURCE: Final = AQI_SOURCE_PM25
TIME_FORMAT: Final = "%H:%M:%S"
DATE_FORMAT: Final = "%Y-%m-%d %H:%M:%S"
DATE_FORMAT_UTC: Final = "%Y-%m-%d %H:%M:%S UTC"
INIT_MSG: Final = """This is a custom integration. When troubleshooting a problem, after
reviewing open and closed issues, and the discussions.

Beta versions may also have addressed issues so look at those.

If all else fails, then open an issue and our community will try to
help: https://github.com/BJReplay/EPA_AirQuality_HA/issues"""
MANUFACTURER: Final = "BJReplay"
TITLE: Final = "EPA Air Quality"
ATTR_CONFIDENCE: Final = "confidence"
ATTR_CONFIDENCE_24H: Final = "confidence_24h"
ATTR_DATA_SOURCE: Final = "data_source"
ATTR_TOTAL_SAMPLE: Final = "total_samples"
ATTR_TOTAL_SAMPLE_24H: Final = "total_samples_24h"
NAME_API: Final = "API"
NAME_AQI: Final = "AQI"
NAME_CO: Final = "CO"
NAME_NO2: Final = "NO2"
NAME_O3: Final = "O3"
NAME_PM10: Final = "PM10"
NAME_PM25: Final = "PM2.5"
NAME_SO2: Final = "SO2"
NAME_VISIBILITY: Final = "Visibility"
PARAM_NAME: Final = "name"
TYPE_AQI: Final = "aqi"
TYPE_AQI_24H: Final = "aqi_24h"
TYPE_AQI_OVERALL: Final = "aqi_overall"
TYPE_AQI_OVERALL_24H: Final = "aqi_overall_24h"
TYPE_AQI_PM25: Final = "aqi_pm25"
TYPE_AQI_PM25_24H: Final = "aqi_pm25_24h"
TYPE_PM25_AQI_VALUE: Final = "pm25_aqi_value"
TYPE_PM25_AQI_VALUE_24H: Final = "pm25_aqi_value_24h"
TYPE_PM25: Final = "pm25"
TYPE_PM25_24H: Final = "pm25_24h"
TYPE_PM10: Final = "pm10"
TYPE_PM10_24H: Final = "pm10_24h"
TYPE_PM10_AQI_VALUE: Final = "pm10_aqi_value"
TYPE_PM10_AQI_VALUE_24H: Final = "pm10_aqi_value_24h"
TYPE_PM10_ADVICE: Final = "pm10_advice"
TYPE_PM10_ADVICE_24H: Final = "pm10_advice_24h"
TYPE_NO2: Final = "no2"
TYPE_NO2_24H: Final = "no2_24h"
TYPE_NO2_AQI_VALUE: Final = "no2_aqi_value"
TYPE_NO2_ADVICE: Final = "no2_advice"
TYPE_NO2_ADVICE_24H: Final = "no2_advice_24h"
TYPE_O3: Final = "o3"
TYPE_O3_24H: Final = "o3_24h"
TYPE_O3_AQI_VALUE: Final = "o3_aqi_value"
TYPE_O3_ADVICE: Final = "o3_advice"
TYPE_O3_ADVICE_24H: Final = "o3_advice_24h"
TYPE_SO2: Final = "so2"
TYPE_SO2_24H: Final = "so2_24h"
TYPE_SO2_AQI_VALUE: Final = "so2_aqi_value"
TYPE_SO2_ADVICE: Final = "so2_advice"
TYPE_SO2_ADVICE_24H: Final = "so2_advice_24h"
TYPE_CO: Final = "co"
TYPE_CO_24H: Final = "co_24h"
TYPE_CO_ADVICE: Final = "co_advice"
TYPE_CO_ADVICE_24H: Final = "co_advice_24h"
URL_BASE: Final = "https://gateway.api.epa.vic.gov.au/environmentMonitoring/v1/sites/"
URL_PARAMETERS: Final = "/parameters"
URL_FIND_SITE: Final = "?environmentalSegment=air&location="
URL_LIST_SITE: Final = "?environmentalSegment=air"
GEOMETRY: Final = "geometry"
COORDINATES: Final = "coordinates"
PARAMETERS: Final = "parameters"
DISTANCE: Final = "distance"
HEALTH_PARAMETER: Final = "healthParameter"
TIME_SERIES_NAME: Final = "timeSeriesName"
TIME_SERIES_READINGS: Final = "timeSeriesReadings"
HOURLY: Final = "1HR_AV"
DAILY: Final = "24HR_AV"
READINGS: Final = "readings"
AVERAGE_VALUE: Final = "averageValue"
HEALTH_ADVICE: Final = "healthAdvice"
UNTIL: Final = "until"
CONFIDENCE: Final = "confidence"
TOTAL_SAMPLE: Final = "totalSample"
RECORDS: Final = "records"
SITE_ID: Final = "siteID"
SITE_NAME: Final = "siteName"
SITE_TYPE: Final = "siteType"
SITE_TYPE_SENSOR: Final = "Sensor"
SITE_TYPE_STANDARD: Final = "Standard"
SITE_TYPE_CAMERA: Final = "Camera"
SITE_HEALTH_ADVICES: Final = "siteHealthAdvices"
SCAN_INTERVAL: Final = timedelta(minutes=15)
